apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextjs-app
  annotations:
    nginx.ingress.kubernetes.io/rate-limit: "100"
spec:
  tls:
    - hosts:
        - nextjs.example.com
      secretName: nextjs-app-prod-tls
  rules:
    - host: nextjs.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextjs-app
                port:
                  number: 80
