apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextjs-app
spec:
  tls:
    - hosts:
        - nextjs-dev.example.com
      secretName: nextjs-app-dev-tls
  rules:
    - host: nextjs-dev.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextjs-app
                port:
                  number: 80
